### ISSUE TITLE
Header full height (responsive)

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/fagri#19]
A user would like to make the header full height without having those white gaps when the website is in tablet / mobile view.

Ticket -> https://secure.helpscout.net/conversation/667324258/169802/?folderId=212390

Example -> http://prntscr.com/l4a07b

**Comment by stefan-cotitosu** [comment]
@SilviuDinu I am not sure what is the issue here. Probably there are two whitespaces on the top and bottom of the Big Title section, but is hard to view this in the screenshot.

However, I can't see such an issue on tablet/mobile view. The screenshot above seems to be on Desktop because the hamburger menu toggle is not visible instead of the menu items.

Based on the HelpScout ticket, is this the same issue as [this one](https://github.com/Codeinwp/hestia-pro/issues/1943)? 😄 

Please give me more details about this, so I can investigate. 👍

**Comment by stefan-cotitosu** [comment]
I am closing this because we discussed the issue [here](https://github.com/Codeinwp/hestia-pro/issues/1943).
